// Generated by https://pagedraw.io/pages/8671
import Newsfeed_post from './newsfeed_post';
import React from 'react';
import './facebook_container.css';

function render() {
    return <div className="facebook_container-facebook_container-4">
        <div className="facebook_container-0">
            <div className="facebook_container-0-0" /> 
            <div className="facebook_container-rectangle_6">
                <div className="facebook_container-0-1-0">
                    <div className="facebook_container-rectangle_27">
                        <div className="facebook_container-0-1-0-0-0">
                            <div className="facebook_container-image_3" /> 
                            <input type="text" placeholder="Search Facebook" className="facebook_container-text_input-9" /> 
                            <div className="facebook_container-0-1-0-0-0-2">
                                <div className="facebook_container-0-1-0-0-0-2-0">
                                    <div className="facebook_container-image_36" style={{"backgroundImage": ("url('"+(this.props.user.profile_image)+"')")}} /> 
                                </div>
                            </div>
                            <div className="facebook_container-text_5">
                                { this.props.user.name }
                            </div>
                            <div className="facebook_container-0-1-0-0-0-4">
                                <div className="facebook_container-0-1-0-0-0-4-0">
                                    <div className="facebook_container-rectangle_2" /> 
                                </div>
                            </div>
                            <div className="facebook_container-text_6">Home</div>
                            <div className="facebook_container-0-1-0-0-0-6">
                                <div className="facebook_container-0-1-0-0-0-6-0">
                                    <div className="facebook_container-image_2" /> 
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="facebook_container-0-2" /> 
        </div>
        <div className="facebook_container-1">
            <div className="facebook_container-rectangle_25">
                <div className="facebook_container-1-0-0">
                    <div className="facebook_container-1-0-0-0">
                        <div className="facebook_container-1-0-0-0-0">
                            <div className="facebook_container-rectangle_22">
                                <div className="facebook_container-1-0-0-0-0-0-0">
                                    <div className="facebook_container-image_25" style={{"backgroundImage": ("url('"+(this.props.user.profile_image)+"')")}} /> 
                                    <div className="facebook_container-text_63">
                                        { this.props.user.name }
                                    </div>
                                </div>
                                <div className="facebook_container-1-0-0-0-0-0-1">
                                    <div className="facebook_container-image_37" /> 
                                    <div className="facebook_container-text_3">
                                        Edit Profile
                                    </div>
                                </div>
                                <div className="facebook_container-1-0-0-0-0-0-2">
                                    <div className="facebook_container-image_1" /> 
                                    <div className="facebook_container-text_2">Your Posts</div>
                                </div>
                                <div className="facebook_container-1-0-0-0-0-0-3">
                                    <div className="facebook_container-text_38">FAVORITES</div>
                                </div>
                                <div className="facebook_container-1-0-0-0-0-0-4">
                                    <div className="facebook_container-image_4" /> 
                                    <div className="facebook_container-text_68">News Feed</div>
                                </div>
                                <div className="facebook_container-1-0-0-0-0-0-5">
                                    <div className="facebook_container-image_38" /> 
                                    <div className="facebook_container-text_65">Messages</div>
                                </div>
                                <div className="facebook_container-1-0-0-0-0-0-6">
                                    <div className="facebook_container-image_44" /> 
                                    <div className="facebook_container-text_39">Events</div>
                                </div>
                                <div className="facebook_container-1-0-0-0-0-0-7">
                                    <div className="facebook_container-image_34" /> 
                                    <div className="facebook_container-text_4">Saved</div>
                                </div>
                                <div className="facebook_container-1-0-0-0-0-0-8">
                                    <div className="facebook_container-image_45" /> 
                                    <div className="facebook_container-text_52">
                                        Sale Groups
                                    </div>
                                </div>
                                <div className="facebook_container-1-0-0-0-0-0-9">
                                    <div className="facebook_container-text_54">PAGES</div>
                                </div>
                                <div className="facebook_container-1-0-0-0-0-0-10">
                                    <div className="facebook_container-rectangle-7">
                                        <div className="facebook_container-1-0-0-0-0-0-10-0-0">
                                            <div className="facebook_container-image_6" style={{"backgroundImage": ("url('"+(this.props.page.image)+"')")}} /> 
                                            <div className="facebook_container-text_4-9">
                                                { this.props.page.name }
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div className="facebook_container-1-0-0-0-0-0-11">
                                    <div className="facebook_container-image_21" /> 
                                    <div className="facebook_container-text_42">
                                        Pages Feed
                                    </div>
                                </div>
                                <div className="facebook_container-1-0-0-0-0-0-12">
                                    <div className="facebook_container-image_33" /> 
                                    <div className="facebook_container-text_46">
                                        Like Pages
                                    </div>
                                </div>
                                <div className="facebook_container-1-0-0-0-0-0-13">
                                    <div className="facebook_container-image_16" /> 
                                    <div className="facebook_container-text_45">Create Ad</div>
                                </div>
                                <div className="facebook_container-1-0-0-0-0-0-14">
                                    <div className="facebook_container-image_5" /> 
                                    <div className="facebook_container-text_37">
                                        Create Page
                                    </div>
                                </div>
                                <div className="facebook_container-1-0-0-0-0-0-15">
                                    <div className="facebook_container-text_47">GROUPS</div>
                                </div>
                                <div className="facebook_container-1-0-0-0-0-0-16">
                                    <div className="facebook_container-image_27" /> 
                                    <div className="facebook_container-text_48">
                                        Discover Groups
                                    </div>
                                </div>
                                <div className="facebook_container-1-0-0-0-0-0-17">
                                    <div className="facebook_container-image-9" /> 
                                    <div className="facebook_container-text-0">
                                        Create Group
                                    </div>
                                </div>
                                <div className="facebook_container-1-0-0-0-0-0-18">
                                    <div className="facebook_container-text_36">FRIENDS</div>
                                </div>
                                <div className="facebook_container-1-0-0-0-0-0-19">
                                    <div className="facebook_container-image_39" /> 
                                    <div className="facebook_container-text_44">
                                        Close Friends
                                    </div>
                                </div>
                                <div className="facebook_container-1-0-0-0-0-0-20">
                                    <div className="facebook_container-image_40" /> 
                                    <div className="facebook_container-text_66">Family</div>
                                </div>
                                <div className="facebook_container-1-0-0-0-0-0-21">
                                    <div className="facebook_container-image_8" /> 
                                    <div className="facebook_container-text_55">
                                        { this.props.user.home_town }
                                    </div>
                                </div>
                                <div className="facebook_container-1-0-0-0-0-0-22">
                                    <div className="facebook_container-rectangle_26">
                                        <div className="facebook_container-1-0-0-0-0-0-22-0-0">
                                            <div className="facebook_container-image_22" /> 
                                            <div className="facebook_container-text_62">
                                                { this.props.user.school }
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div className="facebook_container-1-0-0-0-0-0-23">
                                    <div className="facebook_container-text_40">APPS</div>
                                </div>
                                <div className="facebook_container-1-0-0-0-0-0-24">
                                    <div className="facebook_container-image_9" /> 
                                    <div className="facebook_container-text_53">
                                        Live Video
                                    </div>
                                </div>
                                <div className="facebook_container-1-0-0-0-0-0-25">
                                    <div className="facebook_container-image_4-4" /> 
                                    <div className="facebook_container-text_35">Games</div>
                                </div>
                                <div className="facebook_container-1-0-0-0-0-0-26">
                                    <div className="facebook_container-image_29" /> 
                                    <div className="facebook_container-text_57">
                                        On This Day
                                    </div>
                                </div>
                                <div className="facebook_container-1-0-0-0-0-0-27">
                                    <div className="facebook_container-image_28" /> 
                                    <div className="facebook_container-text_43">Photos</div>
                                </div>
                                <div className="facebook_container-1-0-0-0-0-0-28">
                                    <div className="facebook_container-image_35" /> 
                                    <div className="facebook_container-text_58">
                                        Suggest Edits
                                    </div>
                                </div>
                                <div className="facebook_container-1-0-0-0-0-0-29">
                                    <div className="facebook_container-image_2-9" /> 
                                    <div className="facebook_container-text_60">Pokes</div>
                                </div>
                                <div className="facebook_container-1-0-0-0-0-0-30">
                                    <div className="facebook_container-image_32" /> 
                                    <div className="facebook_container-text_61">
                                        Games Feed
                                    </div>
                                </div>
                                <div className="facebook_container-1-0-0-0-0-0-31">
                                    <div className="facebook_container-text_33">INTERESTS</div>
                                </div>
                                <div className="facebook_container-1-0-0-0-0-0-32">
                                    <div className="facebook_container-image_30" /> 
                                    <div className="facebook_container-text_41">
                                        {"Pages and Public F..."}
                                    </div>
                                </div>
                                <div className="facebook_container-1-0-0-0-0-0-33">
                                    <div className="facebook_container-text_50">EVENTS</div>
                                </div>
                                <div className="facebook_container-1-0-0-0-0-0-34">
                                    <div className="facebook_container-image_24" /> 
                                    <div className="facebook_container-text_51">
                                        Create Event
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="facebook_container-1-0-0-1">
                        <div className="facebook_container-1-0-0-1-0">
                            <div className="facebook_container-rectangle_5">
                                <div className="facebook_container-1-0-0-1-0-0-0">
                                    <div className="facebook_container-rectangle_1">
                                        <div className="facebook_container-1-0-0-1-0-0-0-0-0">
                                            <div className="facebook_container-1-0-0-1-0-0-0-0-0-0">
                                                <div className="facebook_container-1-0-0-1-0-0-0-0-0-0-0">
                                                    <div className="facebook_container-image_26" /> 
                                                </div>
                                            </div>
                                            <div className="facebook_container-text_67">
                                                {"Photo/Video"}
                                            </div>
                                            <div className="facebook_container-rectangle_20" /> 
                                            <div className="facebook_container-1-0-0-1-0-0-0-0-0-3">
                                                <div className="facebook_container-1-0-0-1-0-0-0-0-0-3-0">
                                                    <div className="facebook_container-image_43" /> 
                                                </div>
                                            </div>
                                            <div className="facebook_container-text_59">
                                                Photo Album
                                            </div>
                                        </div>
                                        <div className="facebook_container-1-0-0-1-0-0-0-0-1">
                                            <div className="facebook_container-rectangle_24" /> 
                                        </div>
                                        <div className="facebook_container-1-0-0-1-0-0-0-0-2">
                                            <div className="facebook_container-image_42" style={{"backgroundImage": ("url('"+(this.props.user.profile_image)+"')")}} /> 
                                            <input type="text" placeholder="What's on your mind?" value={this.props.postField} onChange={(e) => this.props.setPostField(e.target.value)} onKeyDown={(e) => {if (e.keyCode === 13) this.props.handleNewPost()}} className="facebook_container-post_input-1" /> 
                                        </div>
                                        <div className="facebook_container-1-0-0-1-0-0-0-0-3">
                                            <div className="facebook_container-rectangle_23" /> 
                                        </div>
                                        <div className="facebook_container-1-0-0-1-0-0-0-0-4">
                                            <button type="submit" className="facebook_container-button_5">
                                                <span>Friends</span>
                                            </button>
                                            <button type="submit" onClick={this.props.handleNewPost} className="facebook_container-button-6">
                                                <span>Post</span>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                                <div className="facebook_container-1-0-0-1-0-0-1">
                                    <div className="facebook_container-1-0-0-1-0-0-1-0">
                                        { this.props.posts.map((post, i) => {
                                            return <div key={i} className="facebook_container-rectangle_2-0">
                                                <div className="facebook_container-1-0-0-1-0-0-1-0-0-0-0">
                                                    <div className="facebook_container-newsfeed_post_instance-4">
                                                        <Newsfeed_post post={post} user={{"profile_image": this.props.user.profile_image, "name": ""}} setCommentField={this.props.setCommentField} handleNewComment={this.props.handleNewComment} likePost={this.props.likePost} removeLike={this.props.removeLike} /> 
                                                    </div>
                                                </div>
                                            </div>;
                                        }) }
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="facebook_container-rectangle_13">
                        <div className="facebook_container-1-0-0-2-0">
                            <div className="facebook_container-rectangle_18">
                                <div className="facebook_container-1-0-0-2-0-0-0">
                                    <div className="facebook_container-rectangle_4">
                                        <div className="facebook_container-1-0-0-2-0-0-0-0-0">
                                            <div className="facebook_container-text_22">
                                                YOUR PAGES
                                            </div>
                                        </div>
                                        <div className="facebook_container-1-0-0-2-0-0-0-0-1">
                                            <div className="facebook_container-rectangle_9" /> 
                                        </div>
                                        <div className="facebook_container-1-0-0-2-0-0-0-0-2">
                                            <div className="facebook_container-image_15" style={{"backgroundImage": ("url('"+(this.props.main.my_page_img)+"')")}} /> 
                                            <div className="facebook_container-1-0-0-2-0-0-0-0-2-1">
                                                <div className="facebook_container-1-0-0-2-0-0-0-0-2-1-0">
                                                    <div className="facebook_container-text_23">
                                                        { this.props.main.name }
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div className="facebook_container-1-0-0-2-0-0-0-0-3">
                                            <div className="facebook_container-rectangle_8" /> 
                                        </div>
                                        <div className="facebook_container-1-0-0-2-0-0-0-0-4">
                                            <div className="facebook_container-text_24">
                                                {"You Haven't Posted in 10 Days"}
                                            </div>
                                        </div>
                                        <div className="facebook_container-1-0-0-2-0-0-0-0-5">
                                            <button type="submit" className="facebook_container-button_3">
                                                <span>Write Post</span>
                                            </button>
                                        </div>
                                        <div className="facebook_container-1-0-0-2-0-0-0-0-6">
                                            <div className="facebook_container-rectangle_7" /> 
                                        </div>
                                        <div className="facebook_container-1-0-0-2-0-0-0-0-7">
                                            <div className="facebook_container-text_20">
                                                Latest Unread Message
                                            </div>
                                        </div>
                                        <div className="facebook_container-1-0-0-2-0-0-0-0-8">
                                            <div className="facebook_container-image_14" style={{"backgroundImage": ("url('"+(this.props.main.img_src)+"')")}} /> 
                                            <div className="facebook_container-1-0-0-2-0-0-0-0-8-1">
                                                <div className="facebook_container-1-0-0-2-0-0-0-0-8-1-0">
                                                    <div className="facebook_container-text_21">
                                                        { this.props.main.message }
                                                    </div>
                                                </div>
                                                <div className="facebook_container-1-0-0-2-0-0-0-0-8-1-1">
                                                    <div className="facebook_container-text_1">
                                                        { this.props.main.message_content }
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div className="facebook_container-1-0-0-2-0-0-0-0-9">
                                            <div className="facebook_container-rectangle_6-9" /> 
                                        </div>
                                        <div className="facebook_container-1-0-0-2-0-0-0-0-10">
                                            <div className="facebook_container-1-0-0-2-0-0-0-0-10-0">
                                                <div className="facebook_container-1-0-0-2-0-0-0-0-10-0-0">
                                                    <div className="facebook_container-text_17">This Week</div>
                                                </div>
                                                <div className="facebook_container-1-0-0-2-0-0-0-0-10-0-1">
                                                    <div className="facebook_container-text_18">
                                                        { this.props.main.reach }
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="facebook_container-1-0-0-2-0-0-0-0-10-1">
                                                <div className="facebook_container-1-0-0-2-0-0-0-0-10-1-0">
                                                    <div className="facebook_container-rectangle_11" /> 
                                                </div>
                                            </div>
                                            <div className="facebook_container-1-0-0-2-0-0-0-0-10-2">
                                                <div className="facebook_container-1-0-0-2-0-0-0-0-10-2-0">
                                                    <div className="facebook_container-text_19">
                                                        { this.props.main.people }
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div className="facebook_container-1-0-0-2-0-0-0-0-11">
                                            <div className="facebook_container-1-0-0-2-0-0-0-0-11-0">
                                                <div className="facebook_container-1-0-0-2-0-0-0-0-11-0-0">
                                                    <div className="facebook_container-text_16">
                                                        Post Reach
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="facebook_container-1-0-0-2-0-0-0-0-11-1">
                                                <div className="facebook_container-1-0-0-2-0-0-0-0-11-1-0">
                                                    <div className="facebook_container-text_15">
                                                        People Engaged
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div className="facebook_container-1-0-0-2-0-0-0-0-12">
                                            <div className="facebook_container-rectangle_10" /> 
                                        </div>
                                        <div className="facebook_container-1-0-0-2-0-0-0-0-13">
                                            <div className="facebook_container-text_14">
                                                Recent Posts
                                            </div>
                                        </div>
                                        <div className="facebook_container-1-0-0-2-0-0-0-0-14">
                                            <div className="facebook_container-rectangle_5-3">
                                                <div className="facebook_container-1-0-0-2-0-0-0-0-14-0-0">
                                                    <div className="facebook_container-image_12" /> 
                                                    <div className="facebook_container-1-0-0-2-0-0-0-0-14-0-0-1">
                                                        <div className="facebook_container-1-0-0-2-0-0-0-0-14-0-0-1-0">
                                                            <div className="facebook_container-text_10">
                                                                How to use Pagedraw in your web app
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div className="facebook_container-1-0-0-2-0-0-0-0-15">
                                            <button type="submit" className="facebook_container-button_2">
                                                <span>Boost Post</span>
                                            </button>
                                        </div>
                                        <div className="facebook_container-1-0-0-2-0-0-0-0-16">
                                            <div className="facebook_container-image_11" /> 
                                            <div className="facebook_container-text_11">
                                                Pagedraw 101
                                            </div>
                                        </div>
                                        <div className="facebook_container-1-0-0-2-0-0-0-0-17">
                                            <div className="facebook_container-image_13" /> 
                                            <div className="facebook_container-text_12">See More</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="facebook_container-1-0-0-2-1">
                            <div className="facebook_container-rectangle_17">
                                <div className="facebook_container-1-0-0-2-1-0-0">
                                    <div className="facebook_container-rectangle_14">
                                        <div className="facebook_container-1-0-0-2-1-0-0-0-0">
                                            <div className="facebook_container-image_18" /> 
                                            <div className="facebook_container-text_28">
                                                {"Andre's birthday is today."}
                                            </div>
                                        </div>
                                        <div className="facebook_container-1-0-0-2-1-0-0-0-1">
                                            <div className="facebook_container-rectangle_12" /> 
                                        </div>
                                    </div>
                                </div>
                                <div className="facebook_container-1-0-0-2-1-0-1">
                                    <div className="facebook_container-text_26">TRENDING</div>
                                    <div className="facebook_container-image_20" /> 
                                </div>
                                <div className="facebook_container-1-0-0-2-1-0-2">
                                    <div className="facebook_container-rectangle_16" /> 
                                </div>
                                <div className="facebook_container-1-0-0-2-1-0-3">
                                    <div className="facebook_container-rectangle_2-5">
                                        <div className="facebook_container-1-0-0-2-1-0-3-0-0">
                                            <div className="facebook_container-image_7" /> 
                                            <div className="facebook_container-text_5-5">
                                                {"Pagedraw: Code"}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div className="facebook_container-1-0-0-2-1-0-4">
                                    <div className="facebook_container-image_3-5" /> 
                                    <div className="facebook_container-text_29">See More</div>
                                </div>
                                <div className="facebook_container-1-0-0-2-1-0-5">
                                    <div className="facebook_container-text_6-4">
                                        SUGGESTED PAGES
                                    </div>
                                </div>
                                <div className="facebook_container-1-0-0-2-1-0-6">
                                    <div className="facebook_container-image_19" /> 
                                </div>
                            </div>
                        </div>
                        <div className="facebook_container-1-0-0-2-2">
                            <div className="facebook_container-rectangle_15">
                                <div className="facebook_container-1-0-0-2-2-0-0">
                                    <div className="facebook_container-1-0-0-2-2-0-0-0">
                                        <div className="facebook_container-1-0-0-2-2-0-0-0-0">
                                            <div className="facebook_container-text_3-7">
                                                {"English (US)"}
                                            </div>
                                            <div className="facebook_container-text_32">
                                                {"Español • Português (Brasil) •"}
                                            </div>
                                        </div>
                                        <div className="facebook_container-1-0-0-2-2-0-0-0-1">
                                            <div className="facebook_container-text_31">
                                                {"Français (France) • Deutsch"}
                                            </div>
                                        </div>
                                    </div>
                                    <div className="facebook_container-1-0-0-2-2-0-0-1">
                                        <div className="facebook_container-1-0-0-2-2-0-0-1-0">
                                            <button type="submit" className="facebook_container-button_4">
                                                <span>{"+"}</span>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="facebook_container-1-0-0-2-3">
                            <div className="facebook_container-text_30">
                                {"Privacy • Terms • Advertising • Ad Choices • Cookies "}
                            </div>
                        </div>
                        <div className="facebook_container-1-0-0-2-4">
                            <div className="facebook_container-text_27">
                                {"Facebook © 2016"}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="facebook_container-2" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}