// Generated by https://pagedraw.io/pages/8671
import React from 'react';
import './like_button_2.css';

function render() {
    return <div className="like_button_2">
        { (((this.props.isLiked !== "true") ? "Default" : "Liked") === "Default") ?
            <div className="like_button_2-default-5">
                <div className="like_button_2-0-0-0">
                    <div onClick={this.props.removeCommentLike} className="like_button_2-text_2">
                        Like
                    </div>
                </div>
            </div>
        : null}
        { (((this.props.isLiked !== "true") ? "Default" : "Liked") === "Liked") ?
            <div className="like_button_2-liked-8">
                <div className="like_button_2-1-0-0">
                    <div className="like_button_2-text_2-4">Like</div>
                </div>
            </div>
        : null}
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}