// Generated by https://pagedraw.io/pages/8671
import React from 'react';
import './like_button_1.css';

function render() {
    return <div className="like_button_1">
        { (((this.props.isLiked !== "true") ? "Default" : "Liked") === "Liked") ?
            <div onClick={() => this.props.removeLike(this.props.postId)} className="like_button_1-liked-3">
                <div className="like_button_1-0-0-0">
                    <img src="https://ucarecdn.com/65099688-c676-479a-ac17-c63225fddee6/" className="like_button_1-image_2" /> 
                    <div className="like_button_1-liked-8">Like </div>
                </div>
            </div>
        : null}
        { (((this.props.isLiked !== "true") ? "Default" : "Liked") === "Default") ?
            <div onClick={() => this.props.likePost(this.props.postId)} className="like_button_1-default-5">
                <div className="like_button_1-1-0-0">
                    <div className="like_button_1-rectangle_3">
                        <div className="like_button_1-1-0-0-0-0">
                            <div className="like_button_1-image_5" /> 
                            <div className="like_button_1-like-3">Like </div>
                        </div>
                    </div>
                </div>
            </div>
        : null}
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}