# Generated by https://pagedraw.io/pages/8463
Banner = require './banner'
Projectitem = require './projectitem'
Pageitem = require './pageitem'
PostLink = require './../frontend/post-link'
{SketchDropzone} = require './../pagedraw-requires'
{FigmaModal} = require './../pagedraw-requires'
React = require 'react'
render = ->
    <div className="main">
        <style dangerouslySetInnerHTML={__html: """
            @import url('https://fonts.googleapis.com/css?family=Lato:|Roboto:');
            
            .main {
                display: flex;
                flex-grow: 1;
            }
            
            .main-no_figma-6 {
                display: flex;
                flex-direction: column;
                background: #FFFFFF;
                min-height: 100vh;
                flex-grow: 1;
            }
            
            .main-0-0-0 {
                display: flex;
            }
            
            .main-instance_of_deleted_component-9 {
                flex-grow: 1;
                flex-basis: 0px;
                display: flex;
                flex-direction: column;
            }
            
            .main-0-0-1 {
                display: flex;
                justify-content: center;
            }
            
            .main-body-2 {
                display: flex;
                flex-direction: column;
            }
            
            .main-0-0-1-0-0 {
                display: flex;
            }
            
            .main-sidebar-6 {
                display: flex;
                flex-direction: column;
                padding-top: 45px;
                padding-bottom: 18px;
            }
            
            .main-0-0-1-0-0-0-0 {
                display: flex;
            }
            
            .main-projects-3 {
                display: flex;
                flex-direction: column;
            }
            
            .main-0-0-1-0-0-0-0-0-0 {
                display: flex;
                padding-right: 234px;
            }
            
            .main-text_1 {
                flex-shrink: 0;
                font-family: "Lato", sans-serif;
                color: #000000;
                font-size: 16px;
                line-height: normal;
                letter-spacing: 0px;
                font-weight: bold;
                font-style: normal;
                text-decoration: none;
                text-align: left;
                word-wrap: break-word;
                padding-right: 0.6875px;
            }
            
            .main-0-0-1-0-0-0-0-0-1 {
                display: flex;
                margin-top: 7px;
            }
            
            .main-rectangle_6 {
                width: 294px;
                height: 1px;
                flex-shrink: 0;
                background: rgb(162, 162, 162);
            }
            
            .main-0-0-1-0-0-0-0-0-2 {
                display: flex;
                margin-top: 8px;
            }
            
            .main-0-0-1-0-0-0-0-0-2-0 {
                display: flex;
                flex-direction: column;
            }
            
            .main-project_list-3 {
                display: flex;
                flex-direction: column;
                padding-top: 1px;
                background: rgb(255, 255, 255);
                flex-grow: 1;
            }
            
            .main-0-0-1-0-0-0-0-0-2-0-0-0-0 {
                display: flex;
            }
            
            .main-projectitem_instance-4 {
                flex-shrink: 0;
                display: flex;
                flex-direction: column;
                min-width: 294px;
            }
            
            .main-0-0-1-0-0-0-1 {
                display: flex;
                margin-top: 30px;
            }
            
            .main-collaborators-1 {
                display: flex;
                flex-direction: column;
            }
            
            .main-0-0-1-0-0-0-1-0-0 {
                display: flex;
                padding-right: 195px;
            }
            
            .main-text_14 {
                flex-shrink: 0;
                font-family: "Lato", sans-serif;
                color: #000000;
                font-size: 16px;
                line-height: normal;
                letter-spacing: 0px;
                font-weight: bold;
                font-style: normal;
                text-decoration: none;
                text-align: left;
                word-wrap: break-word;
                padding-right: 0.40625px;
            }
            
            .main-0-0-1-0-0-0-1-0-1 {
                display: flex;
                margin-top: 7px;
            }
            
            .main-rectangle_9 {
                width: 294px;
                height: 1px;
                flex-shrink: 0;
                background: rgb(162, 162, 162);
            }
            
            .main-0-0-1-0-0-0-1-0-2 {
                display: flex;
                margin-top: 8px;
            }
            
            .main-0-0-1-0-0-0-1-0-2-0 {
                display: flex;
                flex-direction: column;
                margin-top: -12px;
            }
            
            .main-collab_list-2 {
                display: flex;
                flex-direction: column;
                padding-bottom: 1px;
                background: rgb(255, 255, 255);
                margin-top: 12px;
                flex-grow: 1;
            }
            
            .main-0-0-1-0-0-0-1-0-2-0-0-0-0 {
                display: flex;
                padding-right: 5px;
            }
            
            .main-0-0-1-0-0-0-1-0-2-0-0-0-0-0 {
                flex-shrink: 0;
                display: flex;
            }
            
            .main-text_9 {
                width: 273px;
                font-family: "Roboto", sans-serif;
                color: rgb(22, 98, 140);
                font-size: 14px;
                line-height: normal;
                letter-spacing: 0px;
                font-weight: normal;
                font-style: normal;
                text-decoration: underline;
                text-align: left;
                word-wrap: break-word;
                flex-grow: 1;
            }
            
            .main-text_10 {
                flex-shrink: 0;
                margin-left: 5px;
                cursor: pointer;
                font-family: "Lato", sans-serif;
                color: rgb(142, 142, 142);
                font-size: 11px;
                line-height: normal;
                letter-spacing: 0px;
                font-weight: normal;
                font-style: normal;
                text-decoration: none;
                text-align: center;
                word-wrap: break-word;
            }
            
            .main-0-0-1-0-0-0-1-0-3 {
                display: flex;
                margin-top: 17px;
            }
            
            .main-text_input_2 {
                width: 242px;
                height: 29px;
                flex-shrink: 0;
                border-radius: 2px;
                font-family: "Lato", sans-serif;
                color: #000;
                font-size: 14px;
                font-weight: normal;
                font-style: normal;
                text-align: left;
                letter-spacing: 0px;
                line-height: normal;
                word-wrap: normal;
                padding: 6px 12px;
                border: 1px solid #cccccc;
            }
            
            .main-button-7 {
                width: 42px;
                height: 29px;
                flex-shrink: 0;
                margin-left: 10px;
                border-radius: 6px;
                background: rgb(99, 60, 252);
                border-width: 0px;
                font-family: "Lato", sans-serif;
                color: #fff;
                font-size: 11px;
                line-height: normal;
                font-weight: normal;
                font-style: normal;
                text-decoration: none;
                text-align: center;
                word-wrap: break-word;
                letter-spacing: normal;
                border: none;
            }
            
            .main-0-0-1-0-0-0-2 {
                display: flex;
                margin-top: 25px;
                padding-left: 1px;
            }
            
            .main-pagedraw_json-6 {
                display: flex;
                flex-direction: column;
            }
            
            .main-0-0-1-0-0-0-2-0-0 {
                display: flex;
                padding-right: 195px;
            }
            
            .main-0-0-1-0-0-0-2-0-0-0 {
                flex-shrink: 0;
                display: flex;
            }
            
            .main-text_3 {
                font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
                color: #000000;
                font-size: 14px;
                line-height: normal;
                letter-spacing: 0px;
                font-weight: bold;
                font-style: normal;
                text-decoration: none;
                text-align: left;
                word-wrap: break-word;
                flex-grow: 1;
            }
            
            .main-0-0-1-0-0-0-2-0-1 {
                display: flex;
                margin-top: 13px;
            }
            
            .main-rectangle_5 {
                display: flex;
                flex-direction: column;
                padding-top: 12px;
                padding-bottom: 11px;
                border-radius: 4px;
                background: rgb(244, 244, 244);
            }
            
            .main-0-0-1-0-0-0-2-0-1-0-0 {
                display: flex;
                padding-left: 14px;
                padding-right: 16px;
            }
            
            .main-text_6 {
                width: 263px;
                flex-shrink: 0;
                font-family: monaco, Consolas, 'Lucida Console', monospace;
                color: rgb(89, 9, 165);
                font-size: 12px;
                line-height: normal;
                letter-spacing: 0px;
                font-weight: normal;
                font-style: normal;
                text-decoration: none;
                text-align: left;
                word-wrap: break-word;
            }
            
            .main-rectangle_1 {
                display: flex;
                flex-direction: column;
                margin-left: 75px;
                padding-top: 45px;
                padding-bottom: 13px;
            }
            
            .main-0-0-1-0-0-1-0 {
                display: flex;
            }
            
            .main-text_11 {
                width: 751px;
                flex-shrink: 0;
                font-family: "Lato", sans-serif;
                color: rgb(45, 45, 47);
                font-size: 40px;
                line-height: normal;
                letter-spacing: 0px;
                font-weight: bold;
                font-style: normal;
                text-decoration: none;
                text-align: left;
                word-wrap: break-word;
            }
            
            .main-0-0-1-0-0-1-1 {
                display: flex;
                margin-top: 15px;
            }
            
            .main-rectangle_7 {
                width: 751px;
                height: 1px;
                flex-shrink: 0;
                background: rgb(154, 154, 154);
            }
            
            .main-0-0-1-0-0-1-2 {
                display: flex;
                margin-top: 9px;
            }
            
            .main-0-0-1-0-0-1-2-0 {
                display: flex;
                flex-direction: column;
                margin-top: -7px;
            }
            
            .main-doc_list-9 {
                display: flex;
                flex-direction: column;
                padding-top: 10px;
                padding-bottom: 9px;
                background: rgba(255, 255, 255, 0);
                margin-top: 7px;
                flex-grow: 1;
            }
            
            .main-0-0-1-0-0-1-2-0-0-0-0 {
                display: flex;
            }
            
            .main-pageitem_instance-2 {
                flex-shrink: 0;
                display: flex;
                flex-direction: column;
                min-width: 751px;
            }
            
            .main-0-0-1-0-0-1-3 {
                display: flex;
                margin-top: 26px;
                padding-left: 1px;
            }
            
            .main-text_input-5 {
                width: 659px;
                height: 36px;
                flex-shrink: 0;
                border-radius: 2px;
                font-family: "Lato", sans-serif;
                color: #000;
                font-size: 14px;
                font-weight: normal;
                font-style: normal;
                text-align: left;
                letter-spacing: 0px;
                line-height: normal;
                word-wrap: normal;
                padding: 6px 12px;
                border: 1px solid #cccccc;
            }
            
            .main-button_2 {
                width: 81px;
                height: 36px;
                flex-shrink: 0;
                margin-left: 10px;
                border-radius: 6px;
                background: rgb(99, 60, 252);
                border-width: 0px;
                font-family: "Lato", sans-serif;
                color: #fff;
                font-size: 11px;
                line-height: normal;
                font-weight: normal;
                font-style: normal;
                text-decoration: none;
                text-align: center;
                word-wrap: break-word;
                letter-spacing: normal;
                border: none;
            }
            
            .main-0-0-1-0-0-1-4 {
                display: flex;
                margin-top: 13px;
                padding-right: 1px;
            }
            
            .main-new_doc_button-4 {
                display: flex;
                flex-direction: column;
                padding-top: 1px;
                padding-bottom: 16px;
                border-radius: 7px;
                cursor: pointer;
                background: rgb(245, 245, 245);
                border: 3px solid rgb(214, 214, 214);
            }
            
            .main-0-0-1-0-0-1-4-0-0-0 {
                display: flex;
                padding-left: 24px;
                padding-right: 121px;
            }
            
            .main-text_7 {
                flex-shrink: 0;
                font-family: "Lato", sans-serif;
                color: rgba(26, 23, 116, 0.6);
                font-size: 90px;
                line-height: 90px;
                letter-spacing: 0px;
                font-weight: bold;
                font-style: normal;
                text-decoration: none;
                text-align: left;
                word-wrap: break-word;
                padding-right: 0.796875px;
            }
            
            .main-0-0-1-0-0-1-4-0-0-0-1 {
                display: flex;
                flex-direction: column;
                margin-left: 5px;
                padding-top: 27px;
                padding-bottom: 2px;
            }
            
            .main-0-0-1-0-0-1-4-0-0-0-1-0 {
                display: flex;
            }
            
            .main-text_13 {
                width: 142px;
                flex-shrink: 0;
                font-family: "Lato", sans-serif;
                color: rgb(26, 23, 116);
                font-size: 18px;
                line-height: normal;
                letter-spacing: 0px;
                font-weight: bold;
                font-style: normal;
                text-decoration: none;
                text-align: left;
                word-wrap: break-word;
            }
            
            .main-0-0-1-0-0-1-4-0-0-0-1-1 {
                display: flex;
                margin-top: 5px;
            }
            
            .main-text_8 {
                width: 142px;
                flex-shrink: 0;
                font-family: "Lato", sans-serif;
                color: #000000;
                font-size: 14px;
                line-height: normal;
                letter-spacing: 0px;
                font-weight: normal;
                font-style: normal;
                text-decoration: none;
                text-align: left;
                word-wrap: break-word;
            }
            
            .main-import_sketch_button-8 {
                display: flex;
                flex-direction: column;
                margin-left: 8px;
                padding-top: 23px;
                padding-bottom: 19px;
                border-radius: 7px;
                cursor: pointer;
                background: rgb(245, 245, 245);
                border: 3px solid rgb(214, 214, 214);
            }
            
            .main-0-0-1-0-0-1-4-1-0-0 {
                display: flex;
                padding-left: 15px;
                padding-right: 159px;
            }
            
            .main-0-0-1-0-0-1-4-1-0-0-0 {
                display: flex;
                flex-direction: column;
                padding-bottom: 4px;
            }
            
            .main-0-0-1-0-0-1-4-1-0-0-0-0 {
                display: flex;
            }
            
            .main-image_2 {
                width: 61px;
                height: 61px;
                flex-shrink: 0;
                background-image: url('https://ucarecdn.com/5a26092e-6389-43d1-8086-3c44f8c44484/');
                background-size: cover;
                background-position: center;
            }
            
            .main-0-0-1-0-0-1-4-1-0-0-1 {
                display: flex;
                flex-direction: column;
                margin-left: 6px;
                padding-top: 5px;
            }
            
            .main-0-0-1-0-0-1-4-1-0-0-1-0 {
                display: flex;
                padding-right: 25px;
            }
            
            .main-text_5 {
                width: 119px;
                flex-shrink: 0;
                font-family: "Lato", sans-serif;
                color: rgb(26, 23, 116);
                font-size: 18px;
                line-height: normal;
                letter-spacing: 0px;
                font-weight: bold;
                font-style: normal;
                text-decoration: none;
                text-align: left;
                word-wrap: break-word;
            }
            
            .main-0-0-1-0-0-1-4-1-0-0-1-1 {
                display: flex;
                margin-top: 4px;
            }
            
            .main-text_4 {
                width: 144px;
                flex-shrink: 0;
                font-family: "Lato", sans-serif;
                color: #000000;
                font-size: 14px;
                line-height: normal;
                letter-spacing: 0px;
                font-weight: normal;
                font-style: normal;
                text-decoration: none;
                text-align: left;
                word-wrap: break-word;
            }
            
            .main-0-0-2 {
                width: 0px;
                flex-grow: 1;
                flex-basis: 0px;
            }
            
            .main-0-0-3 {
                display: flex;
                justify-content: center;
            }
            
            .main-footer-1 {
                display: flex;
                flex-direction: column;
                padding-top: 33px;
                padding-bottom: 17px;
            }
            
            .main-0-0-3-0-0 {
                display: flex;
                padding-right: 2px;
            }
            
            .main-hr-8 {
                width: 1118px;
                height: 1px;
                flex-shrink: 0;
                background: #E4E4E4;
            }
            
            .main-0-0-3-0-1 {
                display: flex;
                margin-top: 12px;
                padding-left: 871px;
                padding-right: 6px;
            }
            
            .main-0-0-3-0-1-0 {
                display: flex;
                flex-direction: column;
                padding-top: 29px;
                padding-bottom: 7px;
            }
            
            .main-0-0-3-0-1-0-0 {
                display: flex;
            }
            
            .main-text_15 {
                flex-shrink: 0;
                font-family: "Lato", sans-serif;
                color: rgba(16, 16, 16, 0.87);
                font-size: 12px;
                line-height: normal;
                letter-spacing: 0px;
                font-weight: normal;
                font-style: normal;
                text-decoration: none;
                text-align: right;
                word-wrap: break-word;
                padding-right: 0.171875px;
            }
            
            .main-0-0-3-0-1-0-1 {
                display: flex;
                margin-top: 3px;
                padding-left: 102px;
                padding-right: 1px;
            }
            
            .main-text_16 {
                flex-shrink: 0;
                font-family: "Lato", sans-serif;
                color: rgb(37, 37, 37);
                font-size: 10px;
                line-height: normal;
                letter-spacing: 0px;
                font-weight: normal;
                font-style: normal;
                text-decoration: none;
                text-align: right;
                word-wrap: break-word;
                padding-right: 0.65625px;
            }
            
            .main-image_4 {
                width: 49px;
                height: 66px;
                flex-shrink: 0;
                margin-left: 2px;
                border-width: 0px;
            }
            
            .main-figma-8 {
                display: flex;
                flex-direction: column;
                background: #FFFFFF;
                min-height: 100vh;
                flex-grow: 1;
            }
            
            .main-1-0-0 {
                display: flex;
            }
            
            .main-instance_of_deleted_component-7 {
                flex-grow: 1;
                flex-basis: 0px;
                display: flex;
                flex-direction: column;
            }
            
            .main-1-0-1 {
                display: flex;
                justify-content: center;
            }
            
            .main-body-7 {
                display: flex;
                flex-direction: column;
            }
            
            .main-1-0-1-0-0 {
                display: flex;
            }
            
            .main-sidebar-2 {
                display: flex;
                flex-direction: column;
                padding-top: 45px;
                padding-bottom: 18px;
            }
            
            .main-1-0-1-0-0-0-0 {
                display: flex;
            }
            
            .main-projects-4 {
                display: flex;
                flex-direction: column;
            }
            
            .main-1-0-1-0-0-0-0-0-0 {
                display: flex;
                padding-right: 236px;
            }
            
            .main-projects_-3 {
                flex-shrink: 0;
                font-family: "Lato", sans-serif;
                color: #000000;
                font-size: 16px;
                line-height: normal;
                letter-spacing: 0px;
                font-weight: bold;
                font-style: normal;
                text-decoration: none;
                text-align: left;
                word-wrap: break-word;
                padding-right: 0.046875px;
            }
            
            .main-1-0-1-0-0-0-0-0-1 {
                display: flex;
                margin-top: 7px;
            }
            
            .main-rectangle_6-3 {
                width: 294px;
                height: 1px;
                flex-shrink: 0;
                background: rgb(162, 162, 162);
            }
            
            .main-1-0-1-0-0-0-0-0-2 {
                display: flex;
                margin-top: 8px;
            }
            
            .main-1-0-1-0-0-0-0-0-2-0 {
                display: flex;
                flex-direction: column;
            }
            
            .main-project_list-8 {
                display: flex;
                flex-direction: column;
                padding-top: 1px;
                background: rgb(255, 255, 255);
                flex-grow: 1;
            }
            
            .main-1-0-1-0-0-0-0-0-2-0-0-0-0 {
                display: flex;
            }
            
            .main-projectitem-1 {
                flex-shrink: 0;
                display: flex;
                flex-direction: column;
                min-width: 294px;
            }
            
            .main-1-0-1-0-0-0-1 {
                display: flex;
                margin-top: 30px;
            }
            
            .main-collaborators-0 {
                display: flex;
                flex-direction: column;
            }
            
            .main-1-0-1-0-0-0-1-0-0 {
                display: flex;
                padding-right: 197px;
            }
            
            .main-collaborators_-7 {
                flex-shrink: 0;
                font-family: "Lato", sans-serif;
                color: #000000;
                font-size: 16px;
                line-height: normal;
                letter-spacing: 0px;
                font-weight: bold;
                font-style: normal;
                text-decoration: none;
                text-align: left;
                word-wrap: break-word;
                padding-right: 0.484375px;
            }
            
            .main-1-0-1-0-0-0-1-0-1 {
                display: flex;
                margin-top: 7px;
            }
            
            .main-rectangle_9-8 {
                width: 294px;
                height: 1px;
                flex-shrink: 0;
                background: rgb(162, 162, 162);
            }
            
            .main-1-0-1-0-0-0-1-0-2 {
                display: flex;
                margin-top: 8px;
            }
            
            .main-1-0-1-0-0-0-1-0-2-0 {
                display: flex;
                flex-direction: column;
                margin-top: -12px;
            }
            
            .main-collab_list-7 {
                display: flex;
                flex-direction: column;
                padding-bottom: 1px;
                background: rgb(255, 255, 255);
                margin-top: 12px;
                flex-grow: 1;
            }
            
            .main-1-0-1-0-0-0-1-0-2-0-0-0-0 {
                display: flex;
                padding-right: 5px;
            }
            
            .main-1-0-1-0-0-0-1-0-2-0-0-0-0-0 {
                flex-shrink: 0;
                display: flex;
            }
            
            .main-jared_pagedraw_io_-7 {
                width: 273px;
                font-family: "Roboto", sans-serif;
                color: rgb(22, 98, 140);
                font-size: 14px;
                line-height: normal;
                letter-spacing: 0px;
                font-weight: normal;
                font-style: normal;
                text-decoration: underline;
                text-align: left;
                word-wrap: break-word;
                flex-grow: 1;
            }
            
            .main-_-9 {
                flex-shrink: 0;
                margin-left: 5px;
                cursor: pointer;
                font-family: "Lato", sans-serif;
                color: rgb(142, 142, 142);
                font-size: 11px;
                line-height: normal;
                letter-spacing: 0px;
                font-weight: normal;
                font-style: normal;
                text-decoration: none;
                text-align: center;
                word-wrap: break-word;
            }
            
            .main-1-0-1-0-0-0-1-0-3 {
                display: flex;
                margin-top: 17px;
            }
            
            .main-text_input-0 {
                width: 242px;
                height: 29px;
                flex-shrink: 0;
                border-radius: 2px;
                font-family: "Lato", sans-serif;
                color: #000;
                font-size: 14px;
                font-weight: normal;
                font-style: normal;
                text-align: left;
                letter-spacing: 0px;
                line-height: normal;
                word-wrap: normal;
                padding: 6px 12px;
                border: 1px solid #cccccc;
            }
            
            .main-add-3 {
                width: 42px;
                height: 29px;
                flex-shrink: 0;
                margin-left: 10px;
                border-radius: 6px;
                background: rgb(99, 60, 252);
                border-width: 0px;
                font-family: "Lato", sans-serif;
                color: #fff;
                font-size: 11px;
                line-height: normal;
                font-weight: normal;
                font-style: normal;
                text-decoration: none;
                text-align: center;
                word-wrap: break-word;
                letter-spacing: normal;
                border: none;
            }
            
            .main-1-0-1-0-0-0-2 {
                display: flex;
                margin-top: 25px;
                padding-left: 1px;
            }
            
            .main-pagedraw_json-7 {
                display: flex;
                flex-direction: column;
            }
            
            .main-1-0-1-0-0-0-2-0-0 {
                display: flex;
                padding-right: 195px;
            }
            
            .main-1-0-1-0-0-0-2-0-0-0 {
                flex-shrink: 0;
                display: flex;
            }
            
            .main-text_3-9 {
                font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
                color: #000000;
                font-size: 14px;
                line-height: normal;
                letter-spacing: 0px;
                font-weight: bold;
                font-style: normal;
                text-decoration: none;
                text-align: left;
                word-wrap: break-word;
                flex-grow: 1;
            }
            
            .main-1-0-1-0-0-0-2-0-1 {
                display: flex;
                margin-top: 13px;
            }
            
            .main-rectangle_5-7 {
                display: flex;
                flex-direction: column;
                padding-top: 12px;
                padding-bottom: 11px;
                border-radius: 4px;
                background: rgb(244, 244, 244);
            }
            
            .main-1-0-1-0-0-0-2-0-1-0-0 {
                display: flex;
                padding-left: 14px;
                padding-right: 16px;
            }
            
            .main-text_6-9 {
                width: 263px;
                flex-shrink: 0;
                font-family: monaco, Consolas, 'Lucida Console', monospace;
                color: rgb(89, 9, 165);
                font-size: 12px;
                line-height: normal;
                letter-spacing: 0px;
                font-weight: normal;
                font-style: normal;
                text-decoration: none;
                text-align: left;
                word-wrap: break-word;
            }
            
            .main-rectangle_12 {
                display: flex;
                flex-direction: column;
                margin-left: 75px;
                padding-top: 45px;
                padding-bottom: 13px;
            }
            
            .main-1-0-1-0-0-1-0 {
                display: flex;
            }
            
            .main-pied_piper_-1 {
                width: 751px;
                flex-shrink: 0;
                font-family: "Lato", sans-serif;
                color: rgb(45, 45, 47);
                font-size: 40px;
                line-height: normal;
                letter-spacing: 0px;
                font-weight: bold;
                font-style: normal;
                text-decoration: none;
                text-align: left;
                word-wrap: break-word;
            }
            
            .main-1-0-1-0-0-1-1 {
                display: flex;
                margin-top: 15px;
            }
            
            .main-rectangle_7-9 {
                width: 751px;
                height: 1px;
                flex-shrink: 0;
                background: rgb(154, 154, 154);
            }
            
            .main-1-0-1-0-0-1-2 {
                display: flex;
                margin-top: 9px;
            }
            
            .main-1-0-1-0-0-1-2-0 {
                display: flex;
                flex-direction: column;
                margin-top: -7px;
            }
            
            .main-doc_list-1 {
                display: flex;
                flex-direction: column;
                padding-top: 10px;
                padding-bottom: 9px;
                background: rgba(255, 255, 255, 0);
                margin-top: 7px;
                flex-grow: 1;
            }
            
            .main-1-0-1-0-0-1-2-0-0-0-0 {
                display: flex;
            }
            
            .main-pageitem-6 {
                flex-shrink: 0;
                display: flex;
                flex-direction: column;
                min-width: 751px;
            }
            
            .main-1-0-1-0-0-1-3 {
                display: flex;
                margin-top: 26px;
                padding-left: 1px;
            }
            
            .main-text_input-1 {
                width: 659px;
                height: 36px;
                flex-shrink: 0;
                border-radius: 2px;
                font-family: "Lato", sans-serif;
                color: #000;
                font-size: 14px;
                font-weight: normal;
                font-style: normal;
                text-align: left;
                letter-spacing: 0px;
                line-height: normal;
                word-wrap: normal;
                padding: 6px 12px;
                border: 1px solid #cccccc;
            }
            
            .main-add-1 {
                width: 81px;
                height: 36px;
                flex-shrink: 0;
                margin-left: 10px;
                border-radius: 6px;
                background: rgb(99, 60, 252);
                border-width: 0px;
                font-family: "Lato", sans-serif;
                color: #fff;
                font-size: 11px;
                line-height: normal;
                font-weight: normal;
                font-style: normal;
                text-decoration: none;
                text-align: center;
                word-wrap: break-word;
                letter-spacing: normal;
                border: none;
            }
            
            .main-1-0-1-0-0-1-4 {
                display: flex;
                margin-top: 13px;
                padding-right: 1px;
            }
            
            .main-new_doc_button-45 {
                display: flex;
                flex-direction: column;
                padding-top: 1px;
                padding-bottom: 16px;
                border-radius: 7px;
                cursor: pointer;
                background: rgb(245, 245, 245);
                border: 3px solid rgb(214, 214, 214);
            }
            
            .main-1-0-1-0-0-1-4-0-0-0 {
                display: flex;
                padding-left: 24px;
                padding-right: 14px;
            }
            
            .main-text_7-8 {
                flex-shrink: 0;
                font-family: "Lato", sans-serif;
                color: rgba(26, 23, 116, 0.6);
                font-size: 90px;
                line-height: 90px;
                letter-spacing: 0px;
                font-weight: bold;
                font-style: normal;
                text-decoration: none;
                text-align: left;
                word-wrap: break-word;
                padding-right: 0.796875px;
            }
            
            .main-1-0-1-0-0-1-4-0-0-0-1 {
                display: flex;
                flex-direction: column;
                margin-left: 5px;
                padding-top: 27px;
                padding-bottom: 2px;
            }
            
            .main-1-0-1-0-0-1-4-0-0-0-1-0 {
                display: flex;
            }
            
            .main-new_doc_-1 {
                width: 142px;
                flex-shrink: 0;
                font-family: "Lato", sans-serif;
                color: rgb(26, 23, 116);
                font-size: 18px;
                line-height: normal;
                letter-spacing: 0px;
                font-weight: bold;
                font-style: normal;
                text-decoration: none;
                text-align: left;
                word-wrap: break-word;
            }
            
            .main-1-0-1-0-0-1-4-0-0-0-1-1 {
                display: flex;
                margin-top: 5px;
            }
            
            .main-start_from_a_blank_design_-3 {
                width: 142px;
                flex-shrink: 0;
                font-family: "Lato", sans-serif;
                color: #000000;
                font-size: 14px;
                line-height: normal;
                letter-spacing: 0px;
                font-weight: normal;
                font-style: normal;
                text-decoration: none;
                text-align: left;
                word-wrap: break-word;
            }
            
            .main-import_sketch_button-2 {
                display: flex;
                flex-direction: column;
                margin-left: 9px;
                padding-top: 23px;
                padding-bottom: 19px;
                border-radius: 7px;
                cursor: pointer;
                background: rgb(245, 245, 245);
                border: 3px solid rgb(214, 214, 214);
            }
            
            .main-1-0-1-0-0-1-4-1-0-0 {
                display: flex;
                padding-left: 15px;
                padding-right: 12px;
            }
            
            .main-1-0-1-0-0-1-4-1-0-0-0 {
                display: flex;
                flex-direction: column;
                padding-bottom: 4px;
            }
            
            .main-1-0-1-0-0-1-4-1-0-0-0-0 {
                display: flex;
            }
            
            .main-image-2 {
                width: 61px;
                height: 61px;
                flex-shrink: 0;
                background-image: url('https://ucarecdn.com/5a26092e-6389-43d1-8086-3c44f8c44484/');
                background-size: cover;
                background-position: center;
            }
            
            .main-1-0-1-0-0-1-4-1-0-0-1 {
                display: flex;
                flex-direction: column;
                margin-left: 6px;
                padding-top: 5px;
            }
            
            .main-1-0-1-0-0-1-4-1-0-0-1-0 {
                display: flex;
                padding-right: 25px;
            }
            
            .main-text_5-0 {
                width: 119px;
                flex-shrink: 0;
                font-family: "Lato", sans-serif;
                color: rgb(26, 23, 116);
                font-size: 18px;
                line-height: normal;
                letter-spacing: 0px;
                font-weight: bold;
                font-style: normal;
                text-decoration: none;
                text-align: left;
                word-wrap: break-word;
            }
            
            .main-1-0-1-0-0-1-4-1-0-0-1-1 {
                display: flex;
                margin-top: 4px;
            }
            
            .main-text_4-6 {
                width: 144px;
                flex-shrink: 0;
                font-family: "Lato", sans-serif;
                color: #000000;
                font-size: 14px;
                line-height: normal;
                letter-spacing: 0px;
                font-weight: normal;
                font-style: normal;
                text-decoration: none;
                text-align: left;
                word-wrap: break-word;
            }
            
            .main-import_sketch_button-0 {
                display: flex;
                flex-direction: column;
                margin-left: 9px;
                padding-top: 29px;
                padding-bottom: 17px;
                border-radius: 7px;
                cursor: pointer;
                background: rgb(245, 245, 245);
                border: 3px solid rgb(214, 214, 214);
            }
            
            .main-1-0-1-0-0-1-4-2-0-0 {
                display: flex;
                padding-left: 26px;
                padding-right: 2px;
            }
            
            .main-1-0-1-0-0-1-4-2-0-0-0 {
                display: flex;
                flex-direction: column;
                padding-bottom: 4px;
            }
            
            .main-1-0-1-0-0-1-4-2-0-0-0-0 {
                display: flex;
            }
            
            .main-image_3 {
                width: 38px;
                height: 57px;
                flex-shrink: 0;
                border-width: 0px;
            }
            
            .main-1-0-1-0-0-1-4-2-0-0-1 {
                display: flex;
                flex-direction: column;
                margin-left: 18px;
            }
            
            .main-1-0-1-0-0-1-4-2-0-0-1-0 {
                display: flex;
            }
            
            .main-text_5-2 {
                width: 154px;
                flex-shrink: 0;
                font-family: "Lato", sans-serif;
                color: rgb(26, 23, 116);
                font-size: 18px;
                line-height: normal;
                letter-spacing: 0px;
                font-weight: bold;
                font-style: normal;
                text-decoration: none;
                text-align: left;
                word-wrap: break-word;
            }
            
            .main-1-0-1-0-0-1-4-2-0-0-1-1 {
                display: flex;
                margin-top: 5px;
                padding-right: 21px;
            }
            
            .main-text_4-3 {
                width: 133px;
                flex-shrink: 0;
                font-family: "Lato", sans-serif;
                color: #000000;
                font-size: 14px;
                line-height: normal;
                letter-spacing: 0px;
                font-weight: normal;
                font-style: normal;
                text-decoration: none;
                text-align: left;
                word-wrap: break-word;
            }
            
            .main-1-0-2 {
                width: 0px;
                flex-grow: 1;
                flex-basis: 0px;
            }
            
            .main-1-0-3 {
                display: flex;
                justify-content: center;
            }
            
            .main-footer-6 {
                display: flex;
                flex-direction: column;
                padding-top: 33px;
                padding-bottom: 17px;
            }
            
            .main-1-0-3-0-0 {
                display: flex;
                padding-right: 2px;
            }
            
            .main-hr-1 {
                width: 1118px;
                height: 1px;
                flex-shrink: 0;
                background: #E4E4E4;
            }
            
            .main-1-0-3-0-1 {
                display: flex;
                margin-top: 12px;
                padding-left: 871px;
                padding-right: 6px;
            }
            
            .main-1-0-3-0-1-0 {
                display: flex;
                flex-direction: column;
                padding-top: 29px;
                padding-bottom: 7px;
            }
            
            .main-1-0-3-0-1-0-0 {
                display: flex;
            }
            
            .main-making_programming_more_powerful_-5 {
                flex-shrink: 0;
                font-family: "Lato", sans-serif;
                color: rgba(16, 16, 16, 0.87);
                font-size: 12px;
                line-height: normal;
                letter-spacing: 0px;
                font-weight: normal;
                font-style: normal;
                text-decoration: none;
                text-align: right;
                word-wrap: break-word;
                padding-right: 0.171875px;
            }
            
            .main-1-0-3-0-1-0-1 {
                display: flex;
                margin-top: 3px;
                padding-left: 102px;
                padding-right: 1px;
            }
            
            .main-pagedraw_io_2 {
                flex-shrink: 0;
                font-family: "Lato", sans-serif;
                color: rgb(37, 37, 37);
                font-size: 10px;
                line-height: normal;
                letter-spacing: 0px;
                font-weight: normal;
                font-style: normal;
                text-decoration: none;
                text-align: right;
                word-wrap: break-word;
                padding-right: 0.65625px;
            }
            
            .main-image-6 {
                width: 49px;
                height: 66px;
                flex-shrink: 0;
                margin-left: 2px;
                border-width: 0px;
            }
            
            * {
                box-sizing: border-box;
            }
            
            body {
                margin: 0;
            }
            
            button:hover {
                cursor: pointer;
            }
            
            a {
                text-decoration: none;
                color: inherit;
            }
            
            .pd-onhover-parent >.pd-onhover {
                display: none;
            }
            
            .pd-onhover-parent:hover > * {
                display: none;
            }
            
            .pd-onhover-parent:hover > .pd-onhover {
                display: flex;
            }
            
            .pd-onactive-parent > .pd-onactive {
                display: none;
            }
            
            .pd-onactive-parent:active > * {
                display: none;
            }
            
            .pd-onactive-parent:active > .pd-onactive {
                display: flex;
            }
            
            .pd-onactive-parent.pd-onhover-parent:active > .pd-onhover {
                display: none;
            }
        """} /> 
        { if ((if this.props.figma_importing then "figma" else "no_figma") == "no_figma")
            <div className="main-no_figma-6">
                <div className="main-0-0-0">
                    <div className="main-instance_of_deleted_component-9">
                        <Banner username={this.props.current_user.name} logout={(@props.logout)} /> 
                    </div>
                </div>
                <div className="main-0-0-1">
                    <div className="main-body-2">
                        <div className="main-0-0-1-0-0">
                            <div className="main-sidebar-6">
                                <div className="main-0-0-1-0-0-0-0">
                                    <div className="main-projects-3">
                                        <div className="main-0-0-1-0-0-0-0-0-0">
                                            <div className="main-text_1">Projects</div>
                                        </div>
                                        <div className="main-0-0-1-0-0-0-0-0-1">
                                            <div className="main-rectangle_6" /> 
                                        </div>
                                        <div className="main-0-0-1-0-0-0-0-0-2">
                                            <div className="main-0-0-1-0-0-0-0-0-2-0">
                                                { this.props.apps.map (app, i) =>
                                                    <div key={i} className="main-project_list-3">
                                                        <div className="main-0-0-1-0-0-0-0-0-2-0-0-0-0">
                                                            <div className="main-projectitem_instance-4">
                                                                <Projectitem name={app.name} selected={(app.id == this.props.app.id)} onClick={(=> @props.handleAppChanged(app.id))} /> 
                                                            </div>
                                                        </div>
                                                    </div>
                                                }
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div className="main-0-0-1-0-0-0-1">
                                    <div className="main-collaborators-1">
                                        <div className="main-0-0-1-0-0-0-1-0-0">
                                            <div className="main-text_14">Collaborators</div>
                                        </div>
                                        <div className="main-0-0-1-0-0-0-1-0-1">
                                            <div className="main-rectangle_9" /> 
                                        </div>
                                        <div className="main-0-0-1-0-0-0-1-0-2">
                                            <div className="main-0-0-1-0-0-0-1-0-2-0">
                                                { this.props.app.users.map (user, i) =>
                                                    <div key={i} className="main-collab_list-2">
                                                        <div className="main-0-0-1-0-0-0-1-0-2-0-0-0-0">
                                                            <a href="mailto:#{user.email}" className="main-0-0-1-0-0-0-1-0-2-0-0-0-0-0">
                                                                <div className="main-text_9">{ user.email }</div>
                                                            </a>
                                                            <div onClick={=>@props.handleCollaboratorDelete(user.id)} className="main-text_10">
                                                                {"╳"}
                                                            </div>
                                                        </div>
                                                    </div>
                                                }
                                            </div>
                                        </div>
                                        <div className="main-0-0-1-0-0-0-1-0-3">
                                            <input type="text" placeholder="add new collaborator" value={@props.collaboratorField} onChange={(e) => @props.setState collaboratorField: e.target.value} className="main-text_input_2" /> 
                                            <button type="submit" onClick={@props.handleCollaboratorSubmit} className="main-button-7">
                                                <span>Add</span>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                                <div className="main-0-0-1-0-0-0-2">
                                    <div className="main-pagedraw_json-6">
                                        <div className="main-0-0-1-0-0-0-2-0-0">
                                            <a href="https://documentation.pagedraw.io/install" className="main-0-0-1-0-0-0-2-0-0-0">
                                                <div className="main-text_3">{"pagedraw.json"}</div>
                                            </a>
                                        </div>
                                        <div className="main-0-0-1-0-0-0-2-0-1">
                                            <div className="main-rectangle_5">
                                                <div className="main-0-0-1-0-0-0-2-0-1-0-0">
                                                    <div className="main-text_6">
                                                        { this.props.pagedrawJsonBody }
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className="main-rectangle_1">
                                <div className="main-0-0-1-0-0-1-0">
                                    <div className="main-text_11">{ this.props.app.name }</div>
                                </div>
                                <div className="main-0-0-1-0-0-1-1">
                                    <div className="main-rectangle_7" /> 
                                </div>
                                <div className="main-0-0-1-0-0-1-2">
                                    <div className="main-0-0-1-0-0-1-2-0">
                                        { this.props.app.pages.map (page, i) =>
                                            <div key={i} className="main-doc_list-9">
                                                <div className="main-0-0-1-0-0-1-2-0-0-0-0">
                                                    <div className="main-pageitem_instance-2">
                                                        <Pageitem state={"A"} text={page.url} link={("/pages/#{page.id}")} handleDelete={(=> @props.handlePageDelete(page.id))} /> 
                                                    </div>
                                                </div>
                                            </div>
                                        }
                                    </div>
                                </div>
                                <div className="main-0-0-1-0-0-1-3">
                                    <input type="text" placeholder="new doc name" value={@props.pageField} onChange={(e) => @props.setState pageField: e.target.value} className="main-text_input-5" /> 
                                    <button type="submit" onClick={this.props.handlePageSubmit} className="main-button_2">
                                        <span>ADD</span>
                                    </button>
                                </div>
                                <div className="main-0-0-1-0-0-1-4">
                                    <PostLink url={"/apps/#{@props.app.id}/pages/create_blank"} target={""}>
                                        <div className="main-new_doc_button-4">
                                            <div className="main-0-0-1-0-0-1-4-0-0-0">
                                                <div className="main-text_7">{"+"}</div>
                                                <div className="main-0-0-1-0-0-1-4-0-0-0-1">
                                                    <div className="main-0-0-1-0-0-1-4-0-0-0-1-0">
                                                        <div className="main-text_13">New Doc</div>
                                                    </div>
                                                    <div className="main-0-0-1-0-0-1-4-0-0-0-1-1">
                                                        <div className="main-text_8">
                                                            Start from a blank design
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </PostLink>
                                    <SketchDropzone app={(@props.app)}>
                                        <div className="main-import_sketch_button-8">
                                            <div className="main-0-0-1-0-0-1-4-1-0-0">
                                                <div className="main-0-0-1-0-0-1-4-1-0-0-0">
                                                    <div className="main-0-0-1-0-0-1-4-1-0-0-0-0">
                                                        <div className="main-image_2" /> 
                                                    </div>
                                                </div>
                                                <div className="main-0-0-1-0-0-1-4-1-0-0-1">
                                                    <div className="main-0-0-1-0-0-1-4-1-0-0-1-0">
                                                        <div className="main-text_5">Import Sketch</div>
                                                    </div>
                                                    <div className="main-0-0-1-0-0-1-4-1-0-0-1-1">
                                                        <div className="main-text_4">
                                                            Click or drop a Sketch file here to upload
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </SketchDropzone>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="main-0-0-2" /> 
                <div className="main-0-0-3">
                    <div className="main-footer-1">
                        <div className="main-0-0-3-0-0">
                            <div className="main-hr-8" /> 
                        </div>
                        <div className="main-0-0-3-0-1">
                            <div className="main-0-0-3-0-1-0">
                                <div className="main-0-0-3-0-1-0-0">
                                    <div className="main-text_15">
                                        Making programming more powerful
                                    </div>
                                </div>
                                <div className="main-0-0-3-0-1-0-1">
                                    <div className="main-text_16">{"Pagedraw.io © 2017"}</div>
                                </div>
                            </div>
                            <img src="https://ucarecdn.com/dcc8b8a1-72a3-4eeb-b397-cf0306fcf8fd/" className="main-image_4" /> 
                        </div>
                    </div>
                </div>
            </div>
        }
        { if ((if this.props.figma_importing then "figma" else "no_figma") == "figma")
            <div className="main-figma-8">
                <div className="main-1-0-0">
                    <div className="main-instance_of_deleted_component-7">
                        <Banner username={this.props.current_user.name} logout={(@props.logout)} /> 
                    </div>
                </div>
                <div className="main-1-0-1">
                    <div className="main-body-7">
                        <div className="main-1-0-1-0-0">
                            <div className="main-sidebar-2">
                                <div className="main-1-0-1-0-0-0-0">
                                    <div className="main-projects-4">
                                        <div className="main-1-0-1-0-0-0-0-0-0">
                                            <div className="main-projects_-3">Projects</div>
                                        </div>
                                        <div className="main-1-0-1-0-0-0-0-0-1">
                                            <div className="main-rectangle_6-3" /> 
                                        </div>
                                        <div className="main-1-0-1-0-0-0-0-0-2">
                                            <div className="main-1-0-1-0-0-0-0-0-2-0">
                                                { this.props.apps.map (app, i) =>
                                                    <div key={i} className="main-project_list-8">
                                                        <div className="main-1-0-1-0-0-0-0-0-2-0-0-0-0">
                                                            <div className="main-projectitem-1">
                                                                <Projectitem name={app.name} selected={(app.id == this.props.app.id)} onClick={(=> @props.handleAppChanged(app.id))} /> 
                                                            </div>
                                                        </div>
                                                    </div>
                                                }
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div className="main-1-0-1-0-0-0-1">
                                    <div className="main-collaborators-0">
                                        <div className="main-1-0-1-0-0-0-1-0-0">
                                            <div className="main-collaborators_-7">Collaborators</div>
                                        </div>
                                        <div className="main-1-0-1-0-0-0-1-0-1">
                                            <div className="main-rectangle_9-8" /> 
                                        </div>
                                        <div className="main-1-0-1-0-0-0-1-0-2">
                                            <div className="main-1-0-1-0-0-0-1-0-2-0">
                                                { this.props.app.users.map (user, i) =>
                                                    <div key={i} className="main-collab_list-7">
                                                        <div className="main-1-0-1-0-0-0-1-0-2-0-0-0-0">
                                                            <a href="mailto:#{user.email}" className="main-1-0-1-0-0-0-1-0-2-0-0-0-0-0">
                                                                <div className="main-jared_pagedraw_io_-7">
                                                                    { user.email }
                                                                </div>
                                                            </a>
                                                            <div onClick={=>@props.handleCollaboratorDelete(user.id)} className="main-_-9">
                                                                {"╳"}
                                                            </div>
                                                        </div>
                                                    </div>
                                                }
                                            </div>
                                        </div>
                                        <div className="main-1-0-1-0-0-0-1-0-3">
                                            <input type="text" placeholder="add new collaborator" value={@props.collaboratorField} onChange={(e) => @props.setState collaboratorField: e.target.value} className="main-text_input-0" /> 
                                            <button type="submit" onClick={@props.handleCollaboratorSubmit} className="main-add-3">
                                                <span>Add</span>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                                <div className="main-1-0-1-0-0-0-2">
                                    <div className="main-pagedraw_json-7">
                                        <div className="main-1-0-1-0-0-0-2-0-0">
                                            <a href="https://documentation.pagedraw.io/install" className="main-1-0-1-0-0-0-2-0-0-0">
                                                <div className="main-text_3-9">{"pagedraw.json"}</div>
                                            </a>
                                        </div>
                                        <div className="main-1-0-1-0-0-0-2-0-1">
                                            <div className="main-rectangle_5-7">
                                                <div className="main-1-0-1-0-0-0-2-0-1-0-0">
                                                    <div className="main-text_6-9">
                                                        { this.props.pagedrawJsonBody }
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className="main-rectangle_12">
                                <div className="main-1-0-1-0-0-1-0">
                                    <div className="main-pied_piper_-1">
                                        { this.props.app.name }
                                    </div>
                                </div>
                                <div className="main-1-0-1-0-0-1-1">
                                    <div className="main-rectangle_7-9" /> 
                                </div>
                                <div className="main-1-0-1-0-0-1-2">
                                    <div className="main-1-0-1-0-0-1-2-0">
                                        { this.props.app.pages.map (page, i) =>
                                            <div key={i} className="main-doc_list-1">
                                                <div className="main-1-0-1-0-0-1-2-0-0-0-0">
                                                    <div className="main-pageitem-6">
                                                        <Pageitem state={"A"} text={page.url} link={("/pages/#{page.id}")} handleDelete={(=> @props.handlePageDelete(page.id))} /> 
                                                    </div>
                                                </div>
                                            </div>
                                        }
                                    </div>
                                </div>
                                <div className="main-1-0-1-0-0-1-3">
                                    <input type="text" placeholder="new doc name" value={@props.pageField} onChange={(e) => @props.setState pageField: e.target.value} className="main-text_input-1" /> 
                                    <button type="submit" onClick={this.props.handlePageSubmit} className="main-add-1">
                                        <span>ADD</span>
                                    </button>
                                </div>
                                <div className="main-1-0-1-0-0-1-4">
                                    <PostLink url={"/apps/#{@props.app.id}/pages/create_blank"} target={""}>
                                        <div className="main-new_doc_button-45">
                                            <div className="main-1-0-1-0-0-1-4-0-0-0">
                                                <div className="main-text_7-8">{"+"}</div>
                                                <div className="main-1-0-1-0-0-1-4-0-0-0-1">
                                                    <div className="main-1-0-1-0-0-1-4-0-0-0-1-0">
                                                        <div className="main-new_doc_-1">New Doc</div>
                                                    </div>
                                                    <div className="main-1-0-1-0-0-1-4-0-0-0-1-1">
                                                        <div className="main-start_from_a_blank_design_-3">
                                                            Start from a blank design
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </PostLink>
                                    <SketchDropzone app={(@props.app)}>
                                        <div className="main-import_sketch_button-2">
                                            <div className="main-1-0-1-0-0-1-4-1-0-0">
                                                <div className="main-1-0-1-0-0-1-4-1-0-0-0">
                                                    <div className="main-1-0-1-0-0-1-4-1-0-0-0-0">
                                                        <div className="main-image-2" /> 
                                                    </div>
                                                </div>
                                                <div className="main-1-0-1-0-0-1-4-1-0-0-1">
                                                    <div className="main-1-0-1-0-0-1-4-1-0-0-1-0">
                                                        <div className="main-text_5-0">Import Sketch</div>
                                                    </div>
                                                    <div className="main-1-0-1-0-0-1-4-1-0-0-1-1">
                                                        <div className="main-text_4-6">
                                                            Click or drop a Sketch file here to upload
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </SketchDropzone>
                                    <FigmaModal app={(@props.app)} show_figma_modal={(@props.figma_modal)} figma_access_token={(@props.figma_access_token)}>
                                        <div className="main-import_sketch_button-0">
                                            <div className="main-1-0-1-0-0-1-4-2-0-0">
                                                <div className="main-1-0-1-0-0-1-4-2-0-0-0">
                                                    <div className="main-1-0-1-0-0-1-4-2-0-0-0-0">
                                                        <img src="https://ucarecdn.com/8fb8956e-20d0-4114-b516-a2d8c5e4dd7e/" className="main-image_3" /> 
                                                    </div>
                                                </div>
                                                <div className="main-1-0-1-0-0-1-4-2-0-0-1">
                                                    <div className="main-1-0-1-0-0-1-4-2-0-0-1-0">
                                                        <div className="main-text_5-2">Import from Figma</div>
                                                    </div>
                                                    <div className="main-1-0-1-0-0-1-4-2-0-0-1-1">
                                                        <div className="main-text_4-3">
                                                            Click to specify Figma  file to upload
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </FigmaModal>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="main-1-0-2" /> 
                <div className="main-1-0-3">
                    <div className="main-footer-6">
                        <div className="main-1-0-3-0-0">
                            <div className="main-hr-1" /> 
                        </div>
                        <div className="main-1-0-3-0-1">
                            <div className="main-1-0-3-0-1-0">
                                <div className="main-1-0-3-0-1-0-0">
                                    <div className="main-making_programming_more_powerful_-5">
                                        Making programming more powerful
                                    </div>
                                </div>
                                <div className="main-1-0-3-0-1-0-1">
                                    <div className="main-pagedraw_io_2">
                                        {"Pagedraw.io © 2017"}
                                    </div>
                                </div>
                            </div>
                            <img src="https://ucarecdn.com/dcc8b8a1-72a3-4eeb-b397-cf0306fcf8fd/" className="main-image-6" /> 
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>

module.exports = (props) -> render.apply({props})