// Generated by https://pagedraw.io/pages/8671
import Like_button_1 from './like_button_1';
import Newsfeed_comments_list from './newsfeed_comments_list';
import React from 'react';
import './newsfeed_post.css';

function render() {
    return <div className="newsfeed_post-newsfeed_post-7">
        <div className="newsfeed_post-0">
            <div className="newsfeed_post-rectangle_29">
                <div className="newsfeed_post-0-0-0">
                    <div className="newsfeed_post-0-0-0-0">
                        <div className="newsfeed_post-0-0-0-0-0">
                            <div className="newsfeed_post-image_4" style={{"backgroundImage": ("url('"+(this.props.post.user_profile_image)+"')")}} /> 
                        </div>
                    </div>
                    <div className="newsfeed_post-0-0-0-1">
                        <div className="newsfeed_post-0-0-0-1-0">
                            <div className="newsfeed_post-text_7">
                                { this.props.post.name }
                            </div>
                        </div>
                        <div className="newsfeed_post-0-0-0-1-1">
                            <div className="newsfeed_post-0-0-0-1-1-0">
                                <div className="newsfeed_post-0-0-0-1-1-0-0">
                                    <div className="newsfeed_post-image_5" /> 
                                </div>
                            </div>
                            <div className="newsfeed_post-text_71">
                                { this.props.post.time }
                            </div>
                        </div>
                    </div>
                    <div className="newsfeed_post-0-0-0-2" /> 
                    <div className="newsfeed_post-0-0-0-3">
                        <div className="newsfeed_post-0-0-0-3-0">
                            <div className="newsfeed_post-image_51" /> 
                        </div>
                    </div>
                </div>
                <div className="newsfeed_post-0-0-1">
                    <div className="newsfeed_post-text_6">
                        { this.props.post.content }
                    </div>
                </div>
                <div className="newsfeed_post-0-0-2">
                    <div className="newsfeed_post-rectangle_2" /> 
                </div>
                <div className="newsfeed_post-0-0-3">
                    <div className="newsfeed_post-like_button_1">
                        <Like_button_1 isLiked={this.props.post.isLiked} name={""} likePost={this.props.likePost} removeLike={this.props.removeLike} postId={this.props.post.id} /> 
                    </div>
                    <div className="newsfeed_post-0-0-3-1">
                        <div className="newsfeed_post-0-0-3-1-0">
                            <div className="newsfeed_post-image_48" /> 
                        </div>
                    </div>
                    <div className="newsfeed_post-text_2">Comment</div>
                    <div className="newsfeed_post-0-0-3-3">
                        <div className="newsfeed_post-0-0-3-3-0">
                            <div className="newsfeed_post-image_46" /> 
                        </div>
                    </div>
                    <div className="newsfeed_post-0-0-3-4">
                        <div className="newsfeed_post-0-0-3-4-0">
                            <div className="newsfeed_post-text_72">Share</div>
                        </div>
                    </div>
                </div>
                <div className="newsfeed_post-0-0-4">
                    <div className="newsfeed_post-rectangle_30">
                        <div className="newsfeed_post-0-0-4-0-0">
                            <div className="newsfeed_post-image_47" /> 
                            <div className="newsfeed_post-0-0-4-0-0-1">
                                <div className="newsfeed_post-0-0-4-0-0-1-0">
                                    <div className="newsfeed_post-text_73">
                                        { this.props.post.likes }
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="newsfeed_post-0-0-4-0-1">
                            <div className="newsfeed_post-rectangle_3" /> 
                        </div>
                        <div className="newsfeed_post-0-0-4-0-2">
                            <div className="newsfeed_post-newsfeed_comments_list_instance-4">
                                <Newsfeed_comments_list comments={this.props.post.comments} /> 
                            </div>
                        </div>
                        <div className="newsfeed_post-0-0-4-0-3">
                            <div className="newsfeed_post-image_53" style={{"backgroundImage": ("url('"+(this.props.user.profile_image)+"')")}} /> 
                            <input type="text" placeholder="Write a comment..." value={this.props.post.commentField} onChange={(e) => this.props.setCommentField(this.props.post.id, e.target.value)} onKeyDown={(e) => {if (e.keyCode === 13) this.props.handleNewComment(this.props.post.id)}} className="newsfeed_post-text_input_2" /> 
                            <div className="newsfeed_post-0-0-4-0-3-2">
                                <div className="newsfeed_post-0-0-4-0-3-2-0">
                                    <button type="submit" onClick={() => this.props.handleNewComment(this.props.post.id)} className="newsfeed_post-button-8">
                                        <span>Post</span>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="newsfeed_post-0-1" /> 
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}