// Generated by https://pagedraw.io/pages/8671
import Like_button_2 from './like_button_2';
import React from 'react';
import './newsfeed_comment.css';

function render() {
    return <div className="newsfeed_comment-newsfeed_comment-0">
        <div className="newsfeed_comment-0">
            <div className="newsfeed_comment-rectangle_3">
                <div className="newsfeed_comment-0-0-0">
                    <div className="newsfeed_comment-image_1" style={{"backgroundImage": ("url('"+(this.props.comment.profile_image)+"')")}} /> 
                    <div className="newsfeed_comment-rectangle-7">
                        <div className="newsfeed_comment-0-0-0-1-0">
                            <div className="newsfeed_comment-text_3">
                                { this.props.comment.name }
                            </div>
                            <div className="newsfeed_comment-text_9">
                                { this.props.comment.text_content }
                            </div>
                        </div>
                    </div>
                </div>
                <div className="newsfeed_comment-0-0-1">
                    <div className="newsfeed_comment-like_button_2">
                        <Like_button_2 likeButtonState={""} /> 
                    </div>
                    <div className="newsfeed_comment-text_7">
                        {" • Reply •"}
                    </div>
                    <div className="newsfeed_comment-text_8">
                        { this.props.comment.time }
                    </div>
                </div>
            </div>
            <div className="newsfeed_comment-0-1" /> 
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}